### ISSUE TITLE
Default resty client hard coded to report user agent as terraform-provider-artifactory

### ISSUE THREAD

**Issue by chb0github** [jfrog/terraform-provider-shared#17]
**Describe the bug**
The default resty client is hard coded to report user agent as `terraform-provider-artifactory` - obviously, this is a left over from it's origins. 

**Expected behavior**
The user agent should match the provider using it

**Additional context**
https://github.com/jfrog/terraform-provider-shared/blob/7a0d4d5c11c7f0c1d3de9e6dd4ba3c9c53b91e69/client/client.go#L42-L44

**Comment by alexhung** [comment]
Oops. 😄
