### ISSUE TITLE
ProjectKey does not accept a hyphen where UI does.

### ISSUE THREAD

**Issue by coreyjackwilson** [jfrog/terraform-provider-shared#21]
**Describe the bug**
 The client only accepts alphanumerics where the AF UI accepts hyphens. This needs to be loosened to allow project_key to take hyphens. https://github.com/jfrog/terraform-provider-shared/blob/8fc32aa187f7916c72ae2dfe0e9ea7daf13f9efd/validator/validator.go#L54

**Requirements for and issue**
- [x] A description of the bug
- [x] A fully functioning terraform snippet that can be copy&pasted (no outside files or ENV vars unless that's part of the issue). **If this is not supplied, this issue will likely be closed without any effort expended.**
```
project_key = "depart-bu"

you receive the error `Error: invalid value for project_key (project_key must be 3 - 10 lowercase alphanumeric characters)`
```
- [x] Your version of artifactory (you can `curl` it at `$host/artifactory/api/system/version`
* Artifactory SaaS
- [x] Your version of terraform
* `1.0.6`
- [x] Your version of terraform provider
* `6.11.2`

**Expected behavior**
Hyphens can be used in the project_key property

**Additional context**
We follow a naming scheme of `DEPARTMENT-BUSINESSUNIT` for our project keys. This is blocking our migration to projects and AF SaaS

**Comment by coreyjackwilson** [comment]
@alexhung looks like the fix is in. Thank you. When is this going to get bumped? https://github.com/jfrog/terraform-provider-artifactory/blob/ac22ecd2f1f8cc2d79d8f39c893203d5d6414f7e/go.mod#L12

**Comment by alexhung** [comment]
@coreyjackwilson Should be some time today.
