### ISSUE TITLE
OIDC Token Exchange does not support multiple tokens

### ISSUE THREAD

**Issue by mgriffin13** [jfrog/terraform-provider-shared#68]
**Is your feature request related to a problem? Please describe.**
PR #59 added the ability to use TFC Dynamic Workload Credentials, but the implementation was limited to the default configuration within Terraform. My use-case is that I'm attempting to use multiple Dynamic Workload Credentials within the same workspace, which TFC supports.

See https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials/manual-generation#generating-multiple-tokens

**Describe the solution you'd like**
Given my use-case, I would like to see the JFrog provider accept a parameter where I can supply a TFC config such as "JFROG", then the JFrog provider would look for TFC_WORKLOAD_IDENTITY_TOKEN_JFROG, rather than just default to TFC_WORKLOAD_IDENTITY_TOKEN

**Describe alternatives you've considered**
Alternatives include just continuing to use static credentials

**Comment by alexhung** [comment]
@mgriffin13 Thanks for the suggestion. I've addd this to our plan.

**Comment by alexhung** [comment]
@mgriffin13 Is there a provider you want this to be applied to first?

**Comment by mgriffin13** [comment]
> [@mgriffin13](https://github.com/mgriffin13) Is there a provider you want this to be applied to first?

I'm using both Platform and Artifactory right now. Thanks
